openapi: 3.0.1
info:
  title: Poly API
  description: Endpoints that allow users to execute functions on PolyAPI
  version: 'v1'
servers:
  - url: https://staging.polyapi.io
paths:
  /functions/url/0ede78ac-124d-440f-be6a-65c86fd0275d/execute:
    post:
      operationId: shopifyGetProducts
      summary: Get the products from a particular shopify store. If a store name is not specified, use 'darko-demo-store' for the store name
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/storeNameArgs'
      responses:
        "201":
          description: products
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/shopifyGetProductsResponse'
  /functions/url/ec66c324-80fe-4d9a-a5fa-2f7f38384155/execute:
    post:
      operationId: twilioSendSms
      summary: send an sms message to a phone number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/twilioSendSmsArgs'
      responses:
        "201":
          description: details about the sms that was sent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/twilioSendSmsResponse'
components:
  schemas:
    twilioSendSmsArgs:
      type: object
      properties:
        args:
          type: array
          items:
            type: string
          description: first argument is phone number and second is the message
    twilioSendSmsResponse:
      type: object
      properties:
        status:
          type: string
    storeNameArgs:
      type: object
      properties:
        args:
          type: array
          items:
            type: string
          description: store name
    shopifyGetProductsResponse:
      type: object
      properties:
        products:
          type: array
          items:
            type: object
          description: The list of products.