openapi: 3.0.1
info:
  title: Poly API
  description: Endpoints that allow users to execute functions on PolyAPI
  version: 'v1'
servers:
  - url: https://staging.polyapi.io
paths:
  /functions/url/5bc87056-6cae-4910-a67c-c307e4a1074e:
    post:
      operationId: upsRatingGetRate
      description: This API call allows you to retrieve shipping rates for a shipment. The request payload includes shipment details such as shipper and recipient addresses, package dimensions and weight, and shipping service. The response payload includes the shipping rate and other details such as billing weight and service options charges. The API call uses HTTPS protocol and requires authentication. The context is 'ups.rating' and the name is 'rate'.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/upsRatingGetRateArgs'
      responses:
        "201":
          description: products
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/upsRatingGetRateResponse'
components:
  schemas:
    upsRatingGetRateArgs:
      type: object
      properties:
        payload:
          type: object
          properties:
            name:
              type: string
            city:
              type: string
            stateShort:
              type: string
            zipCode:
              type: string
            countryShort:
              type: string
            l:
              type: string
            w:
              type: string
            h:
              type: string
            packageWeight:
              type: string
            token:
              type: string
    upsRatingGetRateResponse:
      # TODO this is fake, still need to do the real version
      type: object
      properties:
        totalCharges:
          type: number
          description: The rate to charge