name: Maven Clean Verify
on:
  pull_request:
    branches:
      - develop

jobs:
  develop:
    name: Maven Clean Verify
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        architecture: x64
    - name: run maven tests
      run: mvn clean verify