name: Release

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**pom.xml'


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - id: checkout
      name: Checkout
      uses: actions/checkout@v4

    - id: gpg-install
      name: Install gpg secret key
      run: |
        # Install gpg secret key
        cat <(echo -e "${{ secrets.MAVEN_GPG_PRIVATE_KEY }}") | gpg --batch --import
        # Verify gpg secret key
        gpg --list-secret-keys --keyid-format LONG

    - id: ssh-setup
      name: Set SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.TAG_SSH_KEY }}

    - id: git-config
      name: Set GIT user name and email
      uses: fregante/setup-git-user@v2

    - id: jdk-setup
      name: Setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
        settings-path: ${{ github.workspace }}

    - id: server-setup
      name: Setup deployment server
      uses: s4u/maven-settings-action@v3.0.0
      with:
        servers: |
          [{
            "id": "ossrh",
            "username": "${{ secrets.DISTRIBUTION_REPOSITORY_RELEASE_USERNAME }}",
            "password": "${{ secrets.DISTRIBUTION_REPOSITORY_RELEASE_PASSWORD }}"
          }]
        properties: '[{"distribution.repository.release.id": "ossrh"}, {"distribution.repository.release.url": "https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/"}]'


    - id: release
      name: Release to production
      run: mvn clean release:clean release:prepare release:perform -B -Darguments="-Ddevelop.api.key=${{ secrets.DEVELOP_SERVER_API_KEY }} -Dprod.eu1.api.key=${{ secrets.PROD_EU1_SERVER_API_KEY }} -Dprod.na1.api.key=${{ secrets.PROD_NA1_SERVER_API_KEY }}" -DpreparationGoals=install

    - id: rollback
      name: Rollback
      if: failure()
      continue-on-error: true
      run: mvn clean release:rollback -B && exit 1
