name: Release

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**pom.xml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Install gpg secret key
      run: |
        # Install gpg secret key
        cat <(echo -e "${{ secrets.MAVEN_GPG_PRIVATE_KEY }}") | gpg --batch --import
        # Verify gpg secret key
        gpg --list-secret-keys --keyid-format LONG

    - name: Set SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.TAG_SSH_KEY }}

    - name: Set GIT user name and email
      uses: fregante/setup-git-user@v2

    - name: Release to production
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
        server-id: ossrh
        server-username: OSSRH_USERNAME
        server-password: OSSRH_PASSWORD
        settings-path: ${{ github.workspace }}
      run: mvn clean release:clean release:prepare release:perform -B -DaltDeploymentRepository=ossrh::https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/ -Darguments="-Ddevelop.api.key=${{ secrets.DEVELOP_SERVER_API_KEY }} -Dprod.eu1.api.key=${{ secrets.PROD_EU1_SERVER_API_KEY }} -Dprod.na1.api.key=${{ secrets.PROD_NA1_SERVER_API_KEY }}" -DpreparationGoals=install -P release
      env:
        OSSRH_USERNAME: ${{ secrets.DISTRIBUTION_REPOSITORY_RELEASE_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.DISTRIBUTION_REPOSITORY_RELEASE_PASSWORD }}