name: Publish NPM package
on:
  pull_request:
    paths:
      - "packages/client/package.json"
    branches:
      - develop
      - main

jobs:
  develop:
    name: Publish NPM package - Development
    runs-on: ubuntu-latest
    if: ${{ github.base_ref == 'refs/heads/develop' }}
      
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Install 
      run: npm ci
    - name: Publish package on NPM 
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  main:
    name: Main docker build and push.
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ADMIN_API_KEY: ${{ secrets.ADMIN_API_KEY }}
      IMAGE: ghcr.io/polyapi/polyapi-main
      
    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: |
        echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u USERNAME --password-stdin
        docker build -t ${{ env.IMAGE }}:${{ github.sha }}-${{ github.run_number }} -f docker/Dockerfile .
        docker push ${{ env.IMAGE }}:${{ github.sha }}-${{ github.run_number }}




    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies and build
      run: npm ci

    - name: Publish pacjage on NPM
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
