name: Docker Image CI
on:
  push:
    branches:
      - develop
      - main

jobs:
  develop:
    name: Development docker build and push.
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/develop' }}

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ADMIN_API_KEY: ${{ secrets.ADMIN_API_KEY }}
      IMAGE: ghcr.io/polyapi/polyapi-dev
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: |
        echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u USERNAME --password-stdin
        docker build -t ${{ env.IMAGE }}:${{ github.sha }}-${{ github.run_number }} -f docker/Dockerfile .
        docker push ${{ env.IMAGE }}:${{ github.sha }}-${{ github.run_number }}

  main:
    name: Main docker build and push.
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ADMIN_API_KEY: ${{ secrets.ADMIN_API_KEY }}
      IMAGE: ghcr.io/polyapi/polyapi-main
      
    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: |
        echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u USERNAME --password-stdin
        docker build -t ${{ env.IMAGE }}:${{ github.sha }}-${{ github.run_number }} -f docker/Dockerfile .
        docker push ${{ env.IMAGE }}:${{ github.sha }}-${{ github.run_number }}