name: Update pre-built base image of node
on:
  push:
    paths:
      - "packages/client"
    branches:
      - develop
      - main

jobs:
  develop:
    name: Development Pre-built image
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/develop' }}
    environment: dev
      
    steps:
    - uses: actions/checkout@v3

    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          client:
            - 'packages/client/package.json'

    - if: steps.changes.outputs.client == 'true'
      name: Hit endpoint and build from schatch pre-built image
      run: |
        curl -X POST \
        https://develop-k8s.polyapi.io/functions/server/prebuilt-base-image \
        -H "Authorization: Bearer ${{ secrets.POLY_SUPER_ADMIN_USER_KEY }}" \
        -H "Content-Type: application/json" \
        -d '{}'
        

  main:
    name: Main Pre-built image
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    environment: main
      
    steps:
    - uses: actions/checkout@v3

    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          client:
            - 'packages/client/package.json'

    - if: steps.changes.outputs.client == 'true'
      name: Hit endpoint and build from schatch pre-built image
      run: |
        curl -X POST \
        https://na1.polyapi.io/functions/server/prebuilt-base-image \
        -H "Authorization: Bearer ${{ secrets.POLY_SUPER_ADMIN_USER_KEY }}" \
        -H "Content-Type: application/json" \
        -d '{}'