name: Docker Image CI
on:
  push:
    branches:
      - develop
      - main

jobs:
  develop:
    name: Development docker build and push.
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/develop' }}

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ADMIN_API_KEY: ${{ secrets.ADMIN_API_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      
    steps:
    # - uses: actions/checkout@v3
    
    # - name: Build the Docker image
    #   run: |
    #     echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u USERNAME --password-stdin
    #     docker build -t ghcr.io/polyapi/polyapi-dev:latest -f docker/Dockerfile .
    #     docker push ghcr.io/polyapi/polyapi-dev:latest

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - uses: tale/kubectl-action@v1
      with:
        base64-kube-config: ${{ secrets.KUBE_CONFIG }}
    - run: |
        kubectl get pods -n development

  staging:
    name: Staging docker build and push.
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ADMIN_API_KEY: ${{ secrets.ADMIN_API_KEY }}
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: |
        echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u USERNAME --password-stdin
        docker build -t ghcr.io/polyapi/polyapi-stg:latest -f docker/Dockerfile .
        docker push ghcr.io/polyapi/polyapi-stg:latest
