name: Update pre-built Java docker image
on:
  push:
    paths:
      - "pom.xml"
    branches:
      - develop
      - main

jobs:
  develop:
    name: Development Pre-built Java image
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/develop' }}
    environment: dev

    steps:
    - uses: actions/checkout@v3


    - name: Hit endpoint and build Java server function pre-built image from scratch
      run: |
        curl -X POST \
        https://dev.polyapi.io/functions/server/prebuilt-base-image \
        -H "Authorization: Bearer ${{ secrets.POLY_SUPER_ADMIN_USER_KEY }}" \
        -H "Content-Type: application/json" \
        -d '{"language": "java"}'


  main:
    name: Main Pre-built Java image
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    environment: main

    steps:
    - uses: actions/checkout@v3

    - name: Hit endpoint and build Java server function pre-built image from scratch
      run: |
        curl --fail-with-body -X POST \
        https://na1.polyapi.io/functions/server/prebuilt-base-image \
        -H "Authorization: Bearer ${{ secrets.POLY_SUPER_ADMIN_USER_KEY }}" \
        -H "Content-Type: application/json" \
        -d '{"language": "java"}'
