name: Docker Image CI
on:
  push:
    branches:
      - develop
      - main

jobs:
  develop:
    name: Development docker build and push.
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/develop' }}

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ADMIN_API_KEY: ${{ secrets.ADMIN_API_KEY }}
      
    steps:
    - uses: actions/checkout@v3

    - name: Read docker image tag
      id: package
      uses: juliangruber/read-file-action@v1
      with:
        path: ./docker/dockerimage-tag-develop.yaml
    
    - name: Build the Docker image
      run: |
        echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u USERNAME --password-stdin
        docker build -t ${{ steps.package.outputs.content }} -f docker/Dockerfile .
        docker push ${{ steps.package.outputs.content }}

  main:
    name: Main docker build and push.
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ADMIN_API_KEY: ${{ secrets.ADMIN_API_KEY }}
      
    steps:
    - uses: actions/checkout@v3

    - name: Read docker image tag
      id: package
      uses: juliangruber/read-file-action@v1
      with:
        path: ./docker/dockerimage-tag-main.yaml

    - name: Build the Docker image
      run: |
        echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u USERNAME --password-stdin
        docker build -t ${{ steps.package.outputs.content }} -f docker/Dockerfile .
        docker push ${{ steps.package.outputs.content }}
